### PR TITLE
Add a small number pad

### PR DESCRIPTION
**Pull request by ByteHamster**
Depends on #1. Must be merged afterwards.

Screenshot:

### CODE REVIEW

**Comment by ByteHamster** [comment]
Hi @mr-kenhoff :) I see you committed some changes, which causes merge conflicts here. Do you want me to update my PRs?

**Comment by mr-kenhoff** [comment]
Hey @ByteHamster . Thanks for your commits :) Very much appreciated!
Since I am currently working on the "backend" side of things (e.g. singleton Calculator, settings provider, print options etc.), I would wait a little bit until I merge your commits, if thats okay? 

Can you estimate how much time you can/want to dedicate for the development of qalculate-android. Shall we discuss/plan the general architecture of the app?

**Comment by ByteHamster** [comment]
> I would wait a little bit until I merge your commits, if thats okay?

I see you also changed UI related things (accent color). If you plan working on the UI as well, I am not sure it will be feasible keeping this PR up-to-date. Maybe having a bit of UI will also make the background changes more fun :)

> Since I am currently working on the "backend" side of things (e.g. singleton Calculator, settings provider, print options etc.)

Do you mean a normal Android settings screen or a libqalculate related settings provider (I don't know anything about libqalculate)?

> Can you estimate how much time you can/want to dedicate for the development of qalculate-android.

I cannot estimate the time, unfortunately. I'm pretty busy with AntennaPod and have a paper deadline next month. While I do plan to contribute a bit, I mainly wanted to bring it to a state that can serve as a replacement for the old calculator app I was using.

> Shall we discuss/plan the general architecture of the app?

Sure, we can definitely discuss. As written above, though, I am not sure how much time I can spend.

**Comment by mr-kenhoff** [comment]
> I see you also changed UI related things (accent color). If you plan working on the UI as well, I am not sure it will be feasible keeping this PR up-to-date. Maybe having a bit of UI will also make the background changes more fun :)

Ahh yes, that were only my changes for the screenshot I posted yesterday night, which I blindly pushed without checking your PR. You're right that a nicer UI makes developing the backend a lot more fun ;) I will resolve the conflict and merge the PR :)

**Comment by ByteHamster** [comment]
I can resolve the conflicts, just give me a minute :)

**Comment by ByteHamster** [comment]
I made `@color/qalculate_pink` slightly darker because that makes it easier to read the white text:

**Comment by mr-kenhoff** [comment]
I just merged your PR. Thanks a lot! Now it's already a useable calculator ;)

**Comment by ByteHamster** [comment]
Nice, thanks! I just uninstalled the old calculator app I was using before :D

**Comment by ByteHamster** [comment]
> Shall we discuss/plan the general architecture of the app?

I created a few issues - some them are about the general architecture. Hope I didn't flood your inbox too much.

**Pull request merged**
